
class HRPortal_PageObjects():

    # def __init__(self,driver):
    #     self.driver=driver

    # locators = {
    #     "username":( 'xpath',"//*[@id='txtUserName']"),
    #     'password':( 'xpath', "//*[@id='txtPassword']"),
    #     "loginbutton":( 'xpath',  "//*[@id='btnLogisn']")
    # }


    username = "//*[@id='txtUserName']"
    password = "//*[@id='txtPassword']"
    loginpage = "//h2[text()='HR PORTAL']"
    loginbutton = "//*[@id='btnLogisn']"
    loginsuccesspage = "//label[text()='HR PORTAL']"
    profileclick = "//*[@id='imgProfile']"
    homeclick = "//*[@id='liHome']/a"
    logout = "//a[@href='Logout.aspx']"
    leavemanagement = "//*[@id='touch_gallery']/div[1]/div/a/i"
    leavemanagementpage = "//*[@id='myCarousel']/div/div/img"
    menu = "//*[@id='iMenu']"
    Bioattendancepage = "//h4[contains(text(),'Bio Attendance')]"
    requestleave = "//*[@id='page-wrapper']/div/div[2]/div/div[1]/div[1]/div/div[2]/a"
    newleaverequestheading = "//*[@id='ContentPlaceHolder1_lblHeading']"
    leavefromdate = "//*[@id='ContentPlaceHolder1_txtLeaveFromDate']"
    fromdatedays = "//table[@class='ui-datepicker-calendar']//tr//td[not(@class=' ui-datepicker-week-end ') and @data-handler='selectDay']/a[1]"
    # fromdateweekoff = "//table[@class='ui-datepicker-calendar']//td[@data-handler='selectDay']//preceding::thead/tr/th/span"
    leavetodate = "//*[@id='ContentPlaceHolder1_txtLeaveToDate']"
    casualcheckbox = "//*[@id='ContentPlaceHolder1_chklstLeaveBalance_0']"
    flexicheckbox = "//*[@id='ContentPlaceHolder1_chklstLeaveBalance_1']"
    earnedcheckbox = "//*[@id='ContentPlaceHolder1_chklstLeaveBalance_2']"
    compoffcheckbox = "//*[@id='ContentPlaceHolder1_chklstLeaveBalance_3']"
    wfhcheckbox = "//*[@id='ContentPlaceHolder1_chklstLeaveBalance_1']"
    cl = "//*[@id='lv_1']/input"
    fl = "//*[@id='lv_2']/input"
    el = "//*[@id='lv_3']/input"
    co = "//*[@id='lv_4']/input"
    shiftypedropdown = "//*[@id='ContentPlaceHolder1_ddlShiftType']"
    pendingtask = "//*[@id='ContentPlaceHolder1_txtPendingTask']"
    reason = "//*[@id='ContentPlaceHolder1_txtLeaveReason']"
    submitbutton ="//*[@id='ContentPlaceHolder1_btnSubmit']"
    leavesummary = "//*[@id='ContentPlaceHolder1_grdLeaveDetails']/tbody/tr"
    requestpermission = "//*[@id='page-wrapper']/div/div[2]/div/div[2]/div[1]/div/div[2]/a"
    permissionclick = "//*[@id='ContentPlaceHolder1_txtPermissionDate']"
    permissiondate="//*[@id='ui-datepicker-div']/table/tbody//following::td[@class=' ui-datepicker-days-cell-over  ui-datepicker-today']"
    permissionfromtime = "//*[@id='ContentPlaceHolder1_txtFromTime']"
    permissiontotime = "//*[@id='ContentPlaceHolder1_txtToTime']"
    permissionreason = "//*[@id='ContentPlaceHolder1_txtReason']"
    permissionsubmit = "//*[@id='ContentPlaceHolder1_btnPermissionSubmit']"
    permissionsummary = "//*[@id='ContentPlaceHolder1_gvPermissionLog']/tbody/tr"
    permissionmoredetails = "//*[@id='page-wrapper']/div/div[2]/div/div[2]/div[3]/div/div/a/b"
    permissiondetailspage = "//*[@id='ContentPlaceHolder1_lblPanelHeading']"
    newpermissionrequest = "//*[@id='page-wrapper']/div/div/div[2]/div/div/div[1]"
    requestwfh = "//*[@id='page-wrapper']/div/div[2]/div/div[4]/div[1]/div/div[2]/a"
    noofwfh = "//*[@id='lv_9']/input"
    requestmode = "//*[@id='ContentPlaceHolder1_dgvODWFH_glblLeaveType_0']"
    requestdays = "//*[@id='ContentPlaceHolder1_dgvODWFH_glblTotalDays_0']"
    wfhsummary = "//*[@id='ContentPlaceHolder1_dgvODWFH']/tbody/tr"
    moredetails = "//*[@id='page-wrapper']/div/div[2]/div/div[1]/div[3]/div/div/a/b"
    leavedetailspage = "//*[@id='ContentPlaceHolder1_lblPageHeader']"
    leavemode = "//*[@id='ContentPlaceHolder1_grdLeaveDetails_glblLeaveType_0']"
    leavecount = "//*[@id='ContentPlaceHolder1_grdLeaveDetails_glblTotalDays_0']"
    leaveapprovestatus = "//table[@id='ContentPlaceHolder1_grdLeaveDetails']/tbody/tr/td/span[contains(text(),'V2E11587')]//following::span[contains(text(),'Approved')]"
    wfhmoredetails = "//*[@id='page-wrapper']/div/div[2]/div/div[4]/div[3]/div/div/a/b"
    wfhapprovestatus = "//table[@id='ContentPlaceHolder1_dgvODWFH']/tbody/tr/td/span[contains(text(),'V2E11587')]//following::span[contains(text(),'Approved')]"
    leavesummarypage = "//*[@id='page-wrapper']/div/div[2]/div/div[1]/div[1]/div/div[1]/a/b"
    # attendancemanagement = "//*[@id='touch_gallery']/div[2]/div/a/i"
    attendancemanagement = "//*[@id='touch_gallery']//following::a/img[@id='AttandanceManagement']//following::i[1]"
    myattendance = "//*[@id='Menu1']/ul/li[2]/a"
    viewattendance = "//*[@id='Menu1:submenu:3']/li[2]/a"
    monthlyattendancepage = "//*[@id='page-wrapper']/div/div/div[2]/div/div/div[1]"
    attendancemonthclick = "//*[@id='ContentPlaceHolder1_ddlMonth']"
    locationselect = "//*[@id='ContentPlaceHolder1_ddlLocation']"
    departmentselect = "//*[@id='ContentPlaceHolder1_ddlDepartment']"
    attendancemonth = "//*[@id='ContentPlaceHolder1_ddlMonth']//following::option[@selected='selected']"
    monthsearch = "//*[@id='ContentPlaceHolder1_btnReportSubmit']"
    leavesearch = "//*[@id='ContentPlaceHolder1_btnSearch']"
    attendancecl = "//*[@id='tblAttendance']//following::span[contains(text(),'CL')]"

    lopattendance = "//*[@id='tblAttendance']/tbody/tr[1]/td[contains(text(),'V2E11587')]//following::td[2]"
    raiselop = "//*[@id='ContentPlaceHolder1_lnkChangeLOPRequest']"
    loprequestnext = "//*[@id='ContentPlaceHolder1_dgvChangeLOPRequest_next']/a"
    attendancepagination = "//*[@id='ContentPlaceHolder1_dgvChangeLOPRequest_paginate']/ul/li[not(contains(@class, 'paginate_button previous')) and  not(contains(@class, 'paginate_button next'))]"
    LOPrequestpage = "//*[@id='ContentPlaceHolder1_lblPopupHeader'][contains(text(),'Change LOP Request')]"
    LOPcomments = "//*[@id='ContentPlaceHolder1_mpetxtRequestchangeLOP']"
    LOPrequestsubmit = "//*[@id='ContentPlaceHolder1_btnSubmit']"
    shifttime = "//*[@id='Menu1']/ul/li[3]/a"
    shifttimemap = "//*[@id='Menu1:submenu:7']/li/a"




#--------------------------------------------supervisor------------------------------------------------------------#
    sleavemanagement = "//*[@id='touch_gallery']/div[2]/div/a/i"
    sleavepermissiondetails = "//*[@id='Menu1']/ul/li[3]/a"
    swfhrequestdetails = "//*[@id='Menu1']/ul/li[4]/a"
    sapproveleave = "//*[@id='Menu1:submenu:9']/li[1]/a"
    sapprovepermission = "//*[@id='Menu1:submenu:9']/li[2]/a"
    sapprovewfh = "//*[@id='Menu1:submenu:20']/li[3]/a"
    sviewteamwfh = "//*[@id='Menu1:submenu:20']/li[4]/a"
    scasualleaveemp = "//table[@id='ContentPlaceHolder1_gvLeaveApproval']/tbody/tr/td/span[contains(text(),'V2E11587')]//following::a[contains(text(),'Approve')]"
    sapproveleavepage = "//*[@id='ContentPlaceHolder1_lblPageHeader']"
    sapprovepermissionpage = "//*[@id='page-wrapper']/div/div[1]/div[3]/div/div/div[1]"
    sapprovepermissioncomments = "//*[@id='ContentPlaceHolder1_txtComments']"
    sapproverequestpage = "//*[@id='ContentPlaceHolder1_lblHeading']"
    sapprovecomments = "//*[@id='ContentPlaceHolder1_txtComments']"
    sapprove = "//*[@id='ContentPlaceHolder1_btnApprove']"
    spermissionapprove = "//*[@id='ContentPlaceHolder1_btnSubmit']"
    sviewteamleave = "//*[@id='Menu1:submenu:9']/li[4]/a"
    sviewteampermission = "//*[@id='Menu1:submenu:9']/li[5]/a"
    sleavedetailspage = "//*[@id='ContentPlaceHolder1_lblHeader']"
    spermissionpage = "//*[@id='ContentPlaceHolder1_lblHead']"
    smonthsearch = "//*[@id='ContentPlaceHolder1_btnSearch']"
    # sattendancemgmt = "//*[@id='touch_gallery']/div[3]/div/a/i"
    sattendancemgmt = "//*[@id='touch_gallery']//following::h4[contains(text(),'Attendance Management')]/parent::div/div/a/img//following::i[1]"
    sattendancemanager = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]"
    # sapprovelop = "//*[@id='Menu1:submenu:7']/li[5]/a"
    sapprovelop = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'Approve LOP Correction')]"
    smarkulop = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'Mark Uninformed Leave')]"
    smarkshiftoff = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'Mark Shift Off / WFH')]"
    sreviewandanalyze = "//*[@id='Menu1']/ul//following::a[contains(text(),'Review And Analyze')]"
    sextensiondetails = "//*[@id='Menu1']/ul//following::a[contains(text(),'Review And Analyze')]//following::a[contains(text(),'Attendance Extension Details')]"
    sextensiondetailspage = "//h4[contains(text(),'Attendance - Extension')]"
    sextensiondetailsempcode = "//*[@id='ContentPlaceHolder1_txtEmployeeCode']"
    sextensiondetailsfromdate = "//*[@id='ContentPlaceHolder1_txtFromDate']"
    sextensiondetailstodate = "//*[@id='ContentPlaceHolder1_txtToDate']"
    sextensiondetailsworkplantab = "//*[@id='aWorkplan']"
    sextensionworkplan = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'Extension Work Plan')]"
    sextensionworkplanpage = "//h4[contains(text(),'Extension Work Plan')]"
    sextensionempcode = "//*[@id='ContentPlaceHolder1_txtEmployeeCode']"
    sextensionfromtime = "//*[@id='ContentPlaceHolder1_txtFromTime']"
    sextensiontotime = "//*[@id='ContentPlaceHolder1_txtToTime']"
    sextensiontype = "//*[@id='ContentPlaceHolder1_ddlExtensionType']"
    sextensioncomments = "//*[@id='ContentPlaceHolder1_txtExtensionComments']"
    sextensionentry = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'Extension Entry')]"
    sextensionentrypage = "//h4[contains(text(),'Attendance - Extension Comments Entry')]"
    sextensionentrysubmit = "//*[@id='ContentPlaceHolder1_mpebtnSubmit']"
    sapproveextensionworkplan = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'Approve Extension Work Plan')]"
    sapproveextensionworkplanpage = "//h4[contains(text(),'Attendance - Extension Work Plan Approval')]"
    snhentry = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'National Holiday Entry')]"
    snhentrypage = "//h4[contains(text(),'National Holidays Entry')]"
    snhentrydate = "//*[@id='ContentPlaceHolder1_txtNHDate']"
    snhentrydateselect = "//table[@class='ui-datepicker-calendar']//following::td[@class=' ui-datepicker-days-cell-over  ui-datepicker-today']//preceding-sibling::td[1]/a"
    snhentryreason = "//*[@id='ContentPlaceHolder1_txtReason']"
    snhentrysubmit = "//*[@id='ContentPlaceHolder1_btnSubmit']"
    sshifttime = "//*[@id='Menu1']/ul/li[4]"
    sshifttimemap = "//*[@id='Menu1:submenu:16']/li/a"
    sshifttimemappage = "//h4[contains(text(),'Map Employee Shift Time')]"
    sshifttimeempcode = "//*[@id='ContentPlaceHolder1_txtCode']"
    sshifttimeempcodesearch = "//*[@id='ContentPlaceHolder1_btnSearch']"
    sshifttimeaddshiftimepage = "//*[@id='ContentPlaceHolder1_lblPopupHeader'][contains(text(),'Add Shift Timing')]"
    sshifttimeupdate = "//*[@id='ContentPlaceHolder1_btnShiftAdd']"
    spayrolldateconfig = "//*[@id='ContentPlaceHolder1_lnkPayrollDateConfig']"
    spayrollstartday = "//*[@id='ContentPlaceHolder1_ddlStartday']/option[24]"
    spayrollendday = "//*[@id='ContentPlaceHolder1_ddlEndday']/option[22]"
    spayrollyear = "//*[@id='ContentPlaceHolder1_ddlYear']/option[3]"
    spayrollsubmit = "//*[@id='ContentPlaceHolder1_btnSubmit']"
    sattendancefreezingdateconfig = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'Attendance Freezing Date Configuration')]"
    sattendancefreezingdatepage = "//h4[contains(text(),'Attendance Freezing')]"
    sattendancefreezingyear = "//*[@id='ContentPlaceHolder1_ddlYear']/option[2]"
    sattendancefreezingmonth = "//*[@id='ContentPlaceHolder1_ddlMonth']/option[3]"
    sattendancefreezingdateclick = "//*[@id='ContentPlaceHolder1_txtFreezingDate']"
    sattendancefreezingdate = "//table[@class='ui-datepicker-calendar']//following::td/a[contains(text(),'21')]"
    sattendancefreezingdate2 = "//table[@class='ui-datepicker-calendar']//following::td[@class=' ui-datepicker-days-cell-over  ui-datepicker-today']/a"
    sattendancefreezingsubmit = "//*[@id='ContentPlaceHolder1_btnSubmit']"
    sulopdashboard = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'ULOP Dashboard')]"
    sapproveshiftoff = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'Approve Shift Off / WFH')]"
    sshiftoffapprovecpage = "//h4[contains(text(),'Approve Shift Off  / WFH Request ')]"
    sapproveshiftdate = "//*[@id='ContentPlaceHolder1_txtAttendanceDate']"
    slopdatedropdown = "//*[@id='ContentPlaceHolder1_ddlLOPDate']"
    slopapprovechangepage = "//h4[contains(text(),'Approve Change LOP Request')]"
    smarkuloppage = "//h4[contains(text(),'Mark Uninformed Leave')]"
    smarkushiftoffpage = "//h4[contains(text(),'Mark Shift Off / WFH')]"
    sulopdashboardpage = "//h4[contains(text(),'ULOP Dashboard')]"
    slopemployeecode = "//*[@id='ContentPlaceHolder1_txtEmployeeCode']"
    sloprecord = "//table[@id='ContentPlaceHolder1_dgvChangeLOPApproval']//following::td[contains(text(),'V2E11587')]//following::td[contains(text(),'Test LOP Request')]//preceding::td/center/span/input"
    slopapprovebutton = "//*[@id='ContentPlaceHolder1_btnApprove']"
    sloprecordsearch = "//*[@id='ContentPlaceHolder1_btnSearch']"
    sattendancemodedropdown = "//*[@id='ContentPlaceHolder1_ddlAttendanceMode']"
    slopapprovecomments = "//*[@id='ContentPlaceHolder1_txtComments']"
    slopapprovepopup = "//*[@id='ContentPlaceHolder1_lblPopupHeader'][contains(text(),'Change LOP Request')]"
    sshiftoffapprovepopup = "//*[@id='ContentPlaceHolder1_lblPopupHeader'][contains(text(),'Shift Off / WFH Request')]"
    slopapproveupdate = "//*[@id='ContentPlaceHolder1_mpebtnUpdate']"
    sviewteamattendance = "//*[@id='Menu1']/ul//following::a[contains(text(),'Attendance Manager')]//following::a[contains(text(),'View Team Attendance')]"
    sviewteamattendancepage = "//h4[contains(text(),'Attendance Report')]"
    sattendancestaffcode = "//*[@id='ContentPlaceHolder1_txtStaffCode']"
    sattendancesearch = "//*[@id='ContentPlaceHolder1_btnReportSearch']"
    sattendanceexcelclick = "//*[@id='ContentPlaceHolder1_imgbtnExportExcel']"
    smarkulopempname = "//*[@id='ContentPlaceHolder1_txtStaffCode']"
    smarkshiftoffcode = "//*[@id='ContentPlaceHolder1_txtEmployeeCode']"
    smarkulopfromdate = "//table[@class='ui-datepicker-calendar']//tr//td[@class=' ui-datepicker-days-cell-over  ui-datepicker-current-day ui-datepicker-today']/ancestor::tbody//following::a[@class='ui-state-default'][last()]"
    smarkuloptodate = "//table[@class='ui-datepicker-calendar']//tr//td[@class=' ui-datepicker-days-cell-over  ui-datepicker-current-day ui-datepicker-today']/ancestor::tbody//following::a[@class='ui-state-default'][last()]"
    smarkulopfromdateclick = "//*[@id='ContentPlaceHolder1_txtFromDate']"
    smarkuloptodateclick = "//*[@id='ContentPlaceHolder1_txtToDate']"
    smarkulopsearch = "//*[@id='ContentPlaceHolder1_btnReportSearch']"
    smarkshiftoffsearch ="//*[@id='ContentPlaceHolder1_btnSearch']"
    smarkulopcomments = "//*[@id='ContentPlaceHolder1_txtComments']"
    smarkulopattendancetype = "//*[@id='ContentPlaceHolder1_ddlAttendanceType']"
    smarkulopsubmit = "//*[@id='ContentPlaceHolder1_btnSubmit']"

    sulopdashboardabsconding = "//*[@id='aAbsconding']"
    sulopdashboardtermination = "//*[@id='aTermination']"
    sulopdashboarduloplist = "//*[@id='aULOPList']"
